server:
  port: 8080
spring:
  application:
    name: showdown
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/showdown
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: very_secret_secret_secret_secret_secret_secret
  expiration: 999999
  token-type: "Bearer "